apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dx
  namespace: '537832106570'
  labels:
    managed-by: google-ai-studio
    cloud.googleapis.com/location: us-west1
  annotations:
    serving.knative.dev/creator: hideki@inoue-kobo.com
    serving.knative.dev/lastModifier: hideki@inoue-kobo.com
    generativelanguage.googleapis.com/type: applet
    run.googleapis.com/ingress: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/build-enable-automatic-updates: 'false'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/sessionAffinity: 'false'
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/base-images: '{"":"us-central1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22"}'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 537832106570-compute@developer.gserviceaccount.com
      containers:
      - image: us-docker.pkg.dev/cloudrun/container/aistudio/applet-proxy
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: API_KEY
          value: YOUR_API_KEY
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
        volumeMounts:
        - name: applet
          mountPath: /app/dist
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      volumes:
      - name: applet
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: true
          volumeAttributes:
            bucketName: ai-studio-bucket-537832106570-us-west1
            mountOptions: only-dir=services/dx/version-5/compiled
      runtimeClassName: run.googleapis.com/linux-base-image-update
  traffic:
  - percent: 100
    latestRevision: true
